### ISSUE TITLE
Getting undefined method `content_type' for nil without any explanation in the log

### ISSUE THREAD

**Issue by Tal-E** [andrcuns/allure-publish-action#45] opened 2024-10-23 09:53 UTC
Hi, Im getting an error `undefined method 'content_type' for nil` without any explanation in the log
I enabled debug mode but I don't see any issues that can say why it fails

Here is the full log

```
/usr/bin/docker run --name c075ee979a5b29594bc99ecf37510d234529_416388 --label 94c075 --workdir /github/workspace --rm -e "AWS_CLI_VERSION" -e "AWS_CLI_ARCH" -e "VERBOSE" -e "LIGHTSAILCTL" -e "BINDIR" -e "INSTALLROOTDIR" -e "ROOTDIR" -e "WORKDIR" -e "ACCOUNT_ID" -e "GITHUB_ROLE_NAME" -e "REGION" -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" -e "RUNNER_REGION" -e "INPUT_STORAGETYPE" -e "INPUT_RESULTSGLOB" -e "INPUT_BUCKET" -e "INPUT_PREFIX" -e "INPUT_BASEURL" -e "INPUT_COPYLATEST" -e "INPUT_IGNOREMISSINGRESULTS" -e "INPUT_DEBUG" -e "INPUT_UPDATEPR" -e "INPUT_SUMMARY" -e "INPUT_SUMMARYTABLETYPE" -e "INPUT_COLLAPSESUMMARY" -e "INPUT_REPORTTITLE" -e "INPUT_FLAKYWARNINGSTATUS" -e "INPUT_COLOR" -e "INPUT_PARALLEL" -e "INPUT_REPORTNAME" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION_PATH" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/_work/_temp/_github_home":"/github/home" -v "/home/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/_work/organization/organization":"/github/workspace" 94c075:ee979a5b29594bc99ecf37510d234529  "--results-glob=.cd_repo/allure_report/tmp/allure_report" "--bucket=allure-report-us-west-2" "--prefix=ci-cd/organization/211" "--update-pr=actions" "--summary=total" "--summary-table-type=markdown" "--collapse-summary=" "--report-title=" "--copy-latest=true" "--ignore-missing-results=true" "--flaky-warning-status=" "--color=true" "--base-url=https://allure-reports-us-west-2.cicd.com/" "--debug=true" "--parallel=8" "s3"
Running allure-report-publisher with arguments: 'upload s3 --results-glob='.cd_repo/allure_report/tmp/allure_report' --bucket=allure-report-us-west-2 --prefix=ci-cd/organization/211 --base-url=https://allure-reports-us-west-2.cicd.com/ --update-pr=actions --summary=total --summary-table-type=markdown --copy-latest --ignore-missing-results --color --debug'
Generating allure report
[✔] generating ... done
== DEBUG LOG OUTPUT ==
[2024-10-23 09:43:08 +0000] Executing command 'which allure'
[2024-10-23 09:43:08 +0000] Glob '.cd_repo/allure_report/tmp/allure_report' found 1 paths
[2024-10-23 09:43:08 +0000] Created tmp folder for common data: '/tmp/allure-results20241023-11-shlhrd'
[2024-10-23 09:43:08 +0000] Created tmp folder for history data: '/tmp/allure-results20241023-11-shlhrd/history'
[2024-10-23 09:43:08 +0000] Downloading previous run history
[2024-10-23 09:43:08 +0000] Downloaded 'categories-trend.json' as '/tmp/allure-results20241023-11-shlhrd/history/categories-trend.json'
[2024-10-23 09:43:08 +0000] Downloaded 'duration-trend.json' as '/tmp/allure-results20241023-11-shlhrd/history/duration-trend.json'
[2024-10-23 09:43:08 +0000] Downloaded 'history-trend.json' as '/tmp/allure-results20241023-11-shlhrd/history/history-trend.json'
[2024-10-23 09:43:08 +0000] Downloaded 'history.json' as '/tmp/allure-results20241023-11-shlhrd/history/history.json'
[2024-10-23 09:43:08 +0000] Downloaded 'retry-trend.json' as '/tmp/allure-results20241023-11-shlhrd/history/retry-trend.json'
[2024-10-23 09:43:08 +0000] Saving ci executor info:
{
  "name": "Github",
  "type": "github",
  "reportName": "AllureReport",
  "reportUrl": "https://allure-reports-us-west-2.cicd.com/ci-cd/organization/211/11476847440/index.html",
  "url": "https://github.com/",
  "buildUrl": "https://github.com/organization/actions/runs/11476847440",
  "buildOrder": "11476847440",
  "buildName": "app-self-test"
}
[2024-10-23 09:43:08 +0000] Saved ci executor info to '/tmp/allure-results20241023-11-shlhrd/executor.json'
[2024-10-23 09:43:08 +0000] Saved ci executor info to '.cd_repo/allure_report/tmp/allure_report/executor.json'
[2024-10-23 09:43:08 +0000] Generating allure report
[2024-10-23 09:43:08 +0000] Executing command 'allure generate --clean --output /tmp/allure-report-1729676588 /tmp/allure-results20241023-11-shlhrd .cd_repo/allure_report/tmp/allure_report'
[2024-10-23 09:43:10 +0000] Generated allure report. Out: Report successfully generated to /tmp/allure-report-1729676588
[2024-10-23 09:43:10 +0000] Removing duplicate entries in '/tmp/allure-report-1729676588/widgets/executors.json'
== DEBUG LOG OUTPUT ==
Uploading allure report to s3
[✖] uploading ... failed
undefined method `content_type' for nil
== DEBUG LOG OUTPUT ==
[2024-10-23 09:43:10 +0000] Uploading report files
[2024-10-23 09:43:10 +0000] Error: undefined method `content_type' for nil
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:135:in `block in upload_to_s3'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:130:in `map'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:130:in `upload_to_s3'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:91:in `upload_report'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/_uploader.rb:66:in `upload'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/commands/upload.rb:202:in `block in upload_report'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/helpers/spinner.rb:37:in `spin'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/helpers/spinner.rb:28:in `spin'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/commands/upload.rb:202:in `upload_report'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/commands/upload.rb:97:in `call'
/usr/local/bundle/gems/dry-cli-1.2.0/lib/dry/cli.rb:117:in `perform_registry'
/usr/local/bundle/gems/dry-cli-1.2.0/lib/dry/cli.rb:66:in `call'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/exe/allure-report-publisher:7:in `<top (required)>'
/usr/local/bundle/bin/allure-report-publisher:25:in `load'
/usr/local/bundle/bin/allure-report-publisher:25:in `<main>'
== DEBUG LOG OUTPUT ==

**Comment by bamanczak** [comment] 2024-11-13 15:49
I face the same issue.
For me it happens for test runs where the number of failures get increased, due to errors in the app under test. This results in larger test reports, as video recordings and screenshots are attached to the report for every failed test.

Initially I thought it's related to the resources limits of the machine publishing the report. However, this fails even after updating to a runner on AWS, based on `ubuntu-2xlarge`

I'm using https://playwright.dev/ as the test framework.

A failing report doesn't have to be **that** big though, even 10MB caused a failure.

Debug log:
```
== DEBUG LOG OUTPUT ==
Uploading allure report to s3
[✖] uploading ... failed
undefined method `content_type' for nil
== DEBUG LOG OUTPUT ==
[2024-11-13 15:33:34 +0000] Uploading report files
[2024-11-13 15:33:34 +0000] Error: undefined method `content_type' for nil
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:135:in `block in upload_to_s3'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:130:in `map'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:130:in `upload_to_s3'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/s3.rb:91:in `upload_report'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/uploaders/_uploader.rb:66:in `upload'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/commands/upload.rb:202:in `block in upload_report'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/helpers/spinner.rb:37:in `spin'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/lib/helpers/spinner.rb:28:in `spin'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/commands/upload.rb:202:in `upload_report'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/lib/allure_report_publisher/commands/upload.rb:97:in `call'
/usr/local/bundle/gems/dry-cli-1.2.0/lib/dry/cli.rb:117:in `perform_registry'
/usr/local/bundle/gems/dry-cli-1.2.0/lib/dry/cli.rb:66:in `call'
/usr/local/bundle/gems/allure-report-publisher-4.2.0/exe/allure-report-publisher:7:in `<top (required)>'
/usr/local/bundle/bin/allure-report-publisher:25:in `load'
/usr/local/bundle/bin/allure-report-publisher:25:in `<main>'
== DEBUG LOG OUTPUT ==
```

**Comment by bamanczak** [comment] 2024-11-22 09:01
I came to conclude that in my case `.imagediff` file is to blame, it doesn't seem to be supported by https://github.com/discourse/mini_mime.

It's used by this plugin https://github.com/allure-framework/allure2/blob/main/plugins/screen-diff-plugin/README.md

**Comment by andrcuns** [comment] 2024-11-22 19:09
I reopened the issue just in case the problem author had was caused by something else

**Comment by andrcuns** [comment] 2024-12-09 10:52
I will go ahead and close this as fixed

**Closed by andrcuns** 2024-12-09 10:52 UTC
